/* Automatically generated by './build/bin/entry.js' */
import Actionsheet from './components/actionsheet/index.js';
import Address from './components/address/index.js';
import Alert from './components/alert/index.js';
import Button from './components/button/index.js';
import Badge from './components/badge/index.js';
import Confirm from './components/confirm/index.js';
import Cell from './components/cell/index.js';
import Clock from './components/clock/index.js';
import CountUp from './components/count-up/index.js';
import CountDown from './components/count-down/index.js';
import CellPreview from './components/cell-preview/index.js';
import DatetimeRange from './components/datetime-range/index.js';
import Datetime from './components/datetime/index.js';
import Dialog from './components/dialog/index.js';
import Divider from './components/divider/index.js';
import Form from './components/form/index.js';
import FormItem from './components/form-item/index.js';
import Flexbox from './components/flexbox/index.js';
import FlexboxItem from './components/flexbox-item/index.js';
import FormPreview from './components/form-preview/index.js';
import Grid from './components/grid/index.js';
import GridItem from './components/grid-item/index.js';
import Group from './components/group/index.js';
import GroupTitle from './components/group-title/index.js';
import Header from './components/header/index.js';
import Icon from './components/icon/index.js';
import InlineDesc from './components/inline-desc/index.js';
import Loading from './components/loading/index.js';
import Marquee from './components/marquee/index.js';
import MarqueeItem from './components/marquee-item/index.js';
import Page from './components/page/index.js';
import Popup from './components/popup/index.js';
import PopupHeader from './components/popup-header/index.js';
import PopupPicker from './components/popup-picker/index.js';
import Picker from './components/picker/index.js';
import Panel from './components/panel/index.js';
import PanelItem from './components/panel-item/index.js';
import Rater from './components/rater/index.js';
import Scroll from './components/scroll/index.js';
import Spinner from './components/spinner/index.js';
import Search from './components/search/index.js';
import Switch from './components/switch/index.js';
import Textarea from './components/textarea/index.js';
import Toast from './components/toast/index.js';
import Tab from './components/tab/index.js';
import TabItem from './components/tab-item/index.js';
import Tabbar from './components/tabbar/index.js';
import TabbarItem from './components/tabbar-item/index.js';
const components = [
   Actionsheet,
 Address,
 Alert,
 Button,
 Badge,
 Confirm,
 Cell,
 Clock,
 CountUp,
 CountDown,
 CellPreview,
 DatetimeRange,
 Datetime,
 Dialog,
 Divider,
 Form,
 FormItem,
 Flexbox,
 FlexboxItem,
 FormPreview,
 Grid,
 GridItem,
 Group,
 GroupTitle,
 Header,
 Icon,
 InlineDesc,
 Loading,
 Marquee,
 MarqueeItem,
 Page,
 Popup,
 PopupHeader,
 PopupPicker,
 Picker,
 Panel,
 PanelItem,
 Rater,
 Scroll,
 Spinner,
 Search,
 Switch,
 Textarea,
 Toast,
 Tab,
 TabItem,
 Tabbar,
 TabbarItem
];

// 指令
import TransferDom from './directives/transfer-dom'
// 插件
import ActionsheetPlugin from './plugins/actionsheet'
import AddressPlugin from './plugins/address'
import AlertPlugin from './plugins/alert'
import DatetimePlugin from './plugins/datetime'
import ConfirmPlugin from './plugins/confirm'
import ConfigPlugin from './plugins/config'
import ToastPlugin from './plugins/toast'
import LoadingPlugin from './plugins/loading'
import DevicePlugin from './plugins/device'

const install = function(Vue, opts = {}) {
  components.forEach(component => {
    Vue.component(component.name, component);
  });

  // 注册指令
  Vue.directive('transfer-dom', TransferDom);
  // 注册组件
  Vue.prototype.$lm = {
    'actionsheet': ActionsheetPlugin,
    'address': AddressPlugin,
    'alert': AlertPlugin,
    'datetime': DatetimePlugin,
    'confirm': ConfirmPlugin,
    'config': ConfigPlugin,
    'toast': ToastPlugin,
    'loading': LoadingPlugin,
    'device': DevicePlugin
  };

};
/* istanbul ignore if */
if (typeof window !== 'undefined' && window.Vue) {
  console.log(window, window.Vue)
  install(window.Vue);
}
export {
   Actionsheet,
 Address,
 Alert,
 Button,
 Badge,
 Confirm,
 Cell,
 Clock,
 CountUp,
 CountDown,
 CellPreview,
 DatetimeRange,
 Datetime,
 Dialog,
 Divider,
 Form,
 FormItem,
 Flexbox,
 FlexboxItem,
 FormPreview,
 Grid,
 GridItem,
 Group,
 GroupTitle,
 Header,
 Icon,
 InlineDesc,
 Loading,
 Marquee,
 MarqueeItem,
 Page,
 Popup,
 PopupHeader,
 PopupPicker,
 Picker,
 Panel,
 PanelItem,
 Rater,
 Scroll,
 Spinner,
 Search,
 Switch,
 Textarea,
 Toast,
 Tab,
 TabItem,
 Tabbar,
 TabbarItem,
  TransferDom,
  ActionsheetPlugin,
  AddressPlugin,
  AlertPlugin,
  DatetimePlugin,
  ConfirmPlugin,
  ConfigPlugin,
  ToastPlugin,
  LoadingPlugin,
  DevicePlugin,
}
export default {
  install,
   Actionsheet,
 Address,
 Alert,
 Button,
 Badge,
 Confirm,
 Cell,
 Clock,
 CountUp,
 CountDown,
 CellPreview,
 DatetimeRange,
 Datetime,
 Dialog,
 Divider,
 Form,
 FormItem,
 Flexbox,
 FlexboxItem,
 FormPreview,
 Grid,
 GridItem,
 Group,
 GroupTitle,
 Header,
 Icon,
 InlineDesc,
 Loading,
 Marquee,
 MarqueeItem,
 Page,
 Popup,
 PopupHeader,
 PopupPicker,
 Picker,
 Panel,
 PanelItem,
 Rater,
 Scroll,
 Spinner,
 Search,
 Switch,
 Textarea,
 Toast,
 Tab,
 TabItem,
 Tabbar,
 TabbarItem,
  TransferDom,
  ActionsheetPlugin,
  AddressPlugin,
  AlertPlugin,
  DatetimePlugin,
  ConfirmPlugin,
  ConfigPlugin,
  ToastPlugin,
  LoadingPlugin,
  DevicePlugin,
};
